# Generated by Django 5.2.6 on 2026-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('audience', models.CharField(blank=True, max_length=400, verbose_name='Для кого')),
                ('body', models.TextField(blank=True, verbose_name='Опис')),
                ('composition', models.JSONField(blank=True, default=list, verbose_name='Склад')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
