# Generated by Django 5.2.15 on 2026-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'title_uk'], 'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='audience',
            new_name='audience_uk',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='body',
            new_name='body_uk',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='composition',
            new_name='composition_uk',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='meta_description',
            new_name='meta_description_uk',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='meta_title',
            new_name='meta_title_uk',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='short_description',
            new_name='short_description_uk',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='title_uk',
        ),
        migrations.AddField(
            model_name='service',
            name='audience_en',
            field=models.CharField(blank=True, max_length=400, verbose_name='Audience'),
        ),
        migrations.AddField(
            model_name='service',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='composition_en',
            field=models.JSONField(blank=True, default=list, verbose_name='Composition'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Title'),
        ),
    ]
