# Generated by Django 5.2.6 on 2026-09-16 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Текст')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-published_at'],
            },
        ),
    ]
