# Generated by Django 5.2.15 on 2026-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='body_uk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='excerpt',
            new_name='excerpt_uk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='meta_description',
            new_name='meta_description_uk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='meta_title',
            new_name='meta_title_uk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_uk',
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
    ]
