# Generated by Django 5.2.6 on 2026-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='Галузь')),
                ('result', models.CharField(blank=True, max_length=300, verbose_name='Результат')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейси',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('role', models.TextField(verbose_name='Посада / опис')),
                ('photo', models.CharField(blank=True, help_text='Наприклад images/team/yesieva.webp', max_length=255, verbose_name='Шлях static (images/...)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Член команди',
                'verbose_name_plural': 'Команда',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
