# Generated by Django 5.2.6 on 2026-09-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_homepage_directions_kicker_homepage_directions_lead_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_cases', to='pages.aboutpage'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pages.aboutpage'),
        ),
    ]
