# Generated by Django 5.2.15 on 2026-09-23 12:04

import django.core.validators
from django.db import migrations, models


def copy_static_team_photos(apps, schema_editor):
    from pathlib import Path

    from django.conf import settings
    from django.core.files.base import File

    TeamMember = apps.get_model("team", "TeamMember")
    static_images = Path(settings.BASE_DIR) / "src" / "core" / "static" / "images"
    for member in TeamMember.objects.all():
        stored = (member.photo.name or "").strip() if member.photo else ""
        if not stored or stored.startswith("team/"):
            continue
        relative = stored[len("images/") :] if stored.startswith("images/") else stored
        src = static_images / relative
        if not src.is_file():
            member.photo = ""
            member.save(update_fields=["photo"])
            continue
        with src.open("rb") as handle:
            member.photo.save(src.name, File(handle), save=True)


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_case_about_teammember_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото'),
        ),
        migrations.RunPython(copy_static_team_photos, migrations.RunPython.noop),
    ]
