# Generated by Django 5.2.15 on 2026-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammember_photo_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['sort_order', 'title_uk'], 'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейси'},
        ),
        migrations.RenameField(
            model_name='case',
            old_name='industry',
            new_name='industry_uk',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='result',
            new_name='result_uk',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='title',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='role',
            new_name='role_uk',
        ),
        migrations.AddField(
            model_name='case',
            name='industry_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='case',
            name='result_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='case',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.TextField(blank=True, verbose_name='Role'),
        ),
    ]
