# Generated by Django 5.2.15 on 2026-09-28 13:26

from django.db import migrations, models

from src.core.content_en import TEAM_NAMES_EN


def fill_names(apps, schema_editor):
    TeamMember = apps.get_model("team", "TeamMember")
    for name_uk, name_en in TEAM_NAMES_EN.items():
        TeamMember.objects.filter(name_uk=name_uk).update(name_en=name_en)


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_bilingual_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['sort_order', 'name_uk'], 'verbose_name': 'Член команди', 'verbose_name_plural': 'Команда'},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='name_uk',
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name'),
        ),
        migrations.RunPython(fill_names, migrations.RunPython.noop),
    ]
