# Generated by Django 5.2.6 on 2026-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.TextField(default='Працюємо з власниками бізнесу, фінансовими директорами та групами компаній, яким потрібна прозора звітність і конструктивний діалог з контролюючими органами.', verbose_name='Лід під заголовком')),
                ('story', models.TextField(blank=True, verbose_name='Текст «Хто ми»')),
                ('stat_1_value', models.CharField(default='19', max_length=20, verbose_name='Цифра 1')),
                ('stat_1_label', models.CharField(default='років на ринку', max_length=120, verbose_name='Підпис 1')),
                ('stat_2_value', models.CharField(default='500', max_length=20, verbose_name='Цифра 2')),
                ('stat_2_label', models.CharField(default='постійних клієнтів', max_length=120, verbose_name='Підпис 2')),
                ('stat_3_value', models.CharField(default='25', max_length=20, verbose_name='Цифра 3')),
                ('stat_3_label', models.CharField(default='успішних проєктів зі статусом критичності', max_length=160, verbose_name='Підпис 3')),
                ('stat_4_value', models.CharField(default='50', max_length=20, verbose_name='Цифра 4')),
                ('stat_4_label', models.CharField(default='супроводжених аудитів', max_length=120, verbose_name='Підпис 4')),
                ('meta_title', models.CharField(blank=True, default='Про нас — Аудит-Перфект', max_length=70, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, default='ПП «АФ «Аудит-Перфект»»: аудит, облік, ТЦ, КІК, військовий облік та юридичний супровід з 2007 року.', max_length=160, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.TextField(default='Супроводжуємо бізнес у звітності, перевірках і призначенні статусу критично важливого підприємства.', verbose_name='Слоган')),
                ('hero_lead', models.TextField(default='Аудит, облік, трансфертне ціноутворення, КІК, військовий облік і юридичний супровід — однією командою.', verbose_name='Підзаголовок банера')),
                ('why_1_title', models.CharField(default='Одна команда', max_length=120, verbose_name='Перевага 1 — заголовок')),
                ('why_1_body', models.CharField(default='Одна команда веде справу до досягнення мети.', max_length=255, verbose_name='Перевага 1 — текст')),
                ('why_2_title', models.CharField(default='Статус критичності', max_length=120, verbose_name='Перевага 2 — заголовок')),
                ('why_2_body', models.CharField(default='Супровід на кожному етапі до позитивного результату.', max_length=255, verbose_name='Перевага 2 — текст')),
                ('why_3_title', models.CharField(default='Супровід перевірок', max_length=120, verbose_name='Перевага 3 — заголовок')),
                ('why_3_body', models.CharField(default='Звільняємо бізнес від зайвої витрати часу та нервів.', max_length=255, verbose_name='Перевага 3 — текст')),
                ('meta_title', models.CharField(blank=True, default='Аудит-Перфект — аудит, облік і супровід бізнесу', max_length=70, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, default='Супроводжуємо бізнес у звітності, перевірках і призначенні статусу критично важливого підприємства.', max_length=160, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'Головна',
                'verbose_name_plural': 'Головна',
            },
        ),
    ]
