# Generated by Django 5.2.6 on 2026-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_copy_siteblocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='directions_kicker',
            field=models.CharField(default='Сім напрямів', max_length=80, verbose_name='Напрями — підпис'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_lead',
            field=models.CharField(default='Комплексний супровід бізнесу в одній команді. Деталі напрямів — у каталозі.', max_length=255, verbose_name='Напрями — текст'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_title',
            field=models.CharField(default='Напрями роботи', max_length=120, verbose_name='Напрями — заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_kicker',
            field=models.CharField(default='Стрічка', max_length=80, verbose_name='Новини — підпис'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_title',
            field=models.CharField(default='Новини', max_length=120, verbose_name='Новини — заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_kicker',
            field=models.CharField(default='Підхід', max_length=80, verbose_name='Чому з нами — підпис'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_lead',
            field=models.CharField(default='Одна команда веде справу до досягнення мети.', max_length=255, verbose_name='Чому з нами — лід'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_title',
            field=models.CharField(default='Чому з нами', max_length=120, verbose_name='Чому з нами — заголовок'),
        ),
    ]
