# Generated by Django 5.2.6 on 2026-09-17 13:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_homepage_directions_kicker_homepage_directions_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='certs_kicker',
            field=models.CharField(default='Допуски', max_length=80, verbose_name='Сертифікати — підпис'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certs_lead',
            field=models.CharField(default='Реєстр аудиторів та документи фірми.', max_length=255, verbose_name='Сертифікати — текст'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certs_title',
            field=models.CharField(default='Сертифікати', max_length=120, verbose_name='Сертифікати — заголовок'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Підпис')),
                ('image', models.ImageField(upload_to='certs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Скан / фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати')),
                ('about', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pages.aboutpage')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
