# Generated by Django 5.2.15 on 2026-09-23 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_aboutpage_certs_kicker_aboutpage_certs_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Зображення банера'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_mode',
            field=models.CharField(choices=[('image', 'Одне зображення'), ('slider', 'Слайдер'), ('video', 'Відео')], default='image', max_length=16, verbose_name='Режим банера'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_poster',
            field=models.ImageField(blank=True, help_text='Показується, поки відео вантажиться, і якщо в системі увімкнено «зменшити рух».', upload_to='hero/poster/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Кадр до старту відео'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='MP4 без звуку, короткий цикл. На проді nginx приймає файл до 20 МБ.', upload_to='hero/video/', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='Відео банера'),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/slides/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Зображення')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати')),
                ('home', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Слайд банера',
                'verbose_name_plural': 'Слайди банера',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
