# Generated by Django 5.2.15 on 2026-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepage_hero_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'фото слайдера', 'verbose_name_plural': 'Фото слайдера'},
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='certs_kicker',
            new_name='certs_kicker_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='certs_lead',
            new_name='certs_lead_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='certs_title',
            new_name='certs_title_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='lead',
            new_name='lead_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='meta_description',
            new_name='meta_description_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='meta_title',
            new_name='meta_title_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='stat_1_label',
            new_name='stat_1_label_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='stat_2_label',
            new_name='stat_2_label_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='stat_3_label',
            new_name='stat_3_label_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='stat_4_label',
            new_name='stat_4_label_uk',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='story',
            new_name='story_uk',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='directions_kicker',
            new_name='directions_kicker_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='directions_lead',
            new_name='directions_lead_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='directions_title',
            new_name='directions_title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_lead',
            new_name='hero_lead_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_title',
            new_name='hero_title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='meta_description',
            new_name='meta_description_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='meta_title',
            new_name='meta_title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='news_kicker',
            new_name='news_kicker_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='news_title',
            new_name='news_title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_1_body',
            new_name='why_1_body_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_1_title',
            new_name='why_1_title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_2_body',
            new_name='why_2_body_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_2_title',
            new_name='why_2_title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_3_body',
            new_name='why_3_body_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_3_title',
            new_name='why_3_title_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_kicker',
            new_name='why_kicker_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_lead',
            new_name='why_lead_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='why_title',
            new_name='why_title_uk',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certs_kicker_en',
            field=models.CharField(blank=True, default='Credentials', max_length=80, verbose_name='Certificates kicker'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certs_lead_en',
            field=models.CharField(blank=True, default='The register of auditors and the firm’s documents.', max_length=255, verbose_name='Certificates lead'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certs_title_en',
            field=models.CharField(blank=True, default='Certificates', max_length=120, verbose_name='Certificates title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='lead_en',
            field=models.TextField(blank=True, default='We work with business owners, finance directors and groups of companies that need transparent reporting and a constructive dialogue with regulators.', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description_en',
            field=models.CharField(blank=True, default='Private Enterprise Audit Firm “Audit-Perfect”: audit, accounting, transfer pricing, CFCs, military registration and legal support since 2007.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title_en',
            field=models.CharField(blank=True, default='About us — Audit-Perfect', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_1_label_en',
            field=models.CharField(blank=True, default='years in the market', max_length=120, verbose_name='Label 1'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_2_label_en',
            field=models.CharField(blank=True, default='regular clients', max_length=120, verbose_name='Label 2'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_3_label_en',
            field=models.CharField(blank=True, default='successful critical-status projects', max_length=160, verbose_name='Label 3'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='stat_4_label_en',
            field=models.CharField(blank=True, default='audits we have supported', max_length=120, verbose_name='Label 4'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_en',
            field=models.TextField(blank=True, default='Private Enterprise Audit Firm “Audit-Perfect” started work in 2007. Over the years the firm has grown from an audit practice into a full partner for business.\n\nWe have expanded our areas of work, the professional team and the range of services, responding to clients’ needs and changes in the business environment.\n\nToday we focus on scaling clients’ foreign trade, professional transfer-pricing documentation, keeping controlled foreign companies within the legal framework, setting up military registration, and confirming critical-enterprise status.\n\nOur approach combines audit competence, a close reading of the law and an understanding of what a business actually needs.', verbose_name='Story'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_kicker_en',
            field=models.CharField(blank=True, default='Seven areas', max_length=80, verbose_name='Directions kicker'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_lead_en',
            field=models.CharField(blank=True, default='Full business support from one team. Details are in the catalogue.', max_length=255, verbose_name='Directions lead'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_title_en',
            field=models.CharField(blank=True, default='Areas of work', max_length=120, verbose_name='Directions title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_lead_en',
            field=models.TextField(blank=True, default='Audit, accounting, transfer pricing, CFCs, military registration and legal support — one team.', verbose_name='Hero lead'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=models.TextField(blank=True, default='We support businesses with reporting, reviews and critical-enterprise status.', verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_en',
            field=models.CharField(blank=True, default='We support businesses with reporting, reviews and critical-enterprise status.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_en',
            field=models.CharField(blank=True, default='Audit-Perfect — audit, accounting and business support', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_kicker_en',
            field=models.CharField(blank=True, default='Feed', max_length=80, verbose_name='News kicker'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_title_en',
            field=models.CharField(blank=True, default='News', max_length=120, verbose_name='News title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_1_body_en',
            field=models.CharField(blank=True, default='One team stays with the matter until the goal is reached.', max_length=255, verbose_name='Advantage 1 text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_1_title_en',
            field=models.CharField(blank=True, default='One team', max_length=120, verbose_name='Advantage 1 title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_2_body_en',
            field=models.CharField(blank=True, default='Support at every stage until a positive result.', max_length=255, verbose_name='Advantage 2 text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_2_title_en',
            field=models.CharField(blank=True, default='Critical status', max_length=120, verbose_name='Advantage 2 title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_3_body_en',
            field=models.CharField(blank=True, default='We spare the business unnecessary time and stress.', max_length=255, verbose_name='Advantage 3 text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_3_title_en',
            field=models.CharField(blank=True, default='Review support', max_length=120, verbose_name='Advantage 3 title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_kicker_en',
            field=models.CharField(blank=True, default='Approach', max_length=80, verbose_name='Why kicker'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_lead_en',
            field=models.CharField(blank=True, default='One team stays with the matter until the goal is reached.', max_length=255, verbose_name='Why lead'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_title_en',
            field=models.CharField(blank=True, default='Why us', max_length=120, verbose_name='Why title'),
        ),
    ]
