# Generated by Django 5.2.15 on 2026-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_bilingual_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_description_en',
            field=models.CharField(blank=True, default='Private Enterprise Audit Firm “AUDYT-PERFECT”: audit, accounting, transfer pricing, CFCs, military registration and legal support since 2007.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_title_en',
            field=models.CharField(blank=True, default='About us — AUDYT-PERFECT', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_en',
            field=models.TextField(blank=True, default='Private Enterprise Audit Firm “AUDYT-PERFECT” started work in 2007. Over the years the firm has grown from an audit practice into a full partner for business.\n\nWe have expanded our areas of work, the professional team and the range of services, responding to clients’ needs and changes in the business environment.\n\nToday we focus on scaling clients’ foreign trade, professional transfer-pricing documentation, keeping controlled foreign companies within the legal framework, setting up military registration, and confirming critical-enterprise status.\n\nOur approach combines audit competence, a close reading of the law and an understanding of what a business actually needs.', verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title_en',
            field=models.CharField(blank=True, default='AUDYT-PERFECT — audit, accounting and business support', max_length=70, verbose_name='SEO title'),
        ),
    ]
