# Generated by Django 5.2.6 on 2026-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Аудит-Перфект', max_length=120, verbose_name='Назва')),
                ('tagline', models.CharField(default='Аудиторська фірма', max_length=120, verbose_name='Підпис')),
                ('phone', models.CharField(default='+38 044 355 18 22', max_length=40, verbose_name='Телефон')),
                ('phone_href', models.CharField(default='+380443551822', max_length=40, verbose_name='tel:')),
                ('email', models.EmailField(default='office@auditperfekt.ua', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='вул. Велика Житомирська, 20, Київ', max_length=255, verbose_name='Адреса')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='Карта (embed)')),
                ('registry_url', models.URLField(blank=True, default='https://register.apob.org.ua/uk/search', verbose_name='Реєстр аудиторів')),
                ('registry_number', models.CharField(default='3975', max_length=40, verbose_name='Номер у реєстрі')),
                ('default_meta_title', models.CharField(default='Аудит-Перфект — аудит, облік і супровід бізнесу', max_length=70, verbose_name='SEO title за замовчуванням')),
                ('default_meta_description', models.CharField(default='Супроводжуємо бізнес у звітності, перевірках і призначенні статусу критично важливого підприємства.', max_length=160, verbose_name='SEO description за замовчуванням')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=64, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('html', 'HTML'), ('image', 'Зображення')], default='text', max_length=16)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимий')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'CMS-блок',
                'verbose_name_plural': 'CMS-блоки',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='uniq_siteblock_page_key')],
            },
        ),
    ]
