# Generated by Django 5.2.15 on 2026-09-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='edrpou',
            field=models.CharField(blank=True, default='34971458', max_length=20, verbose_name='ЄДРПОУ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_note',
            field=models.CharField(blank=True, default='Обідня перерва 13:00–14:00.', max_length=255, verbose_name='Примітка до графіка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_weekdays',
            field=models.CharField(default='09:00–18:00', max_length=80, verbose_name='Години Пн–Пт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_weekend',
            field=models.CharField(default='Вихідний', max_length=80, verbose_name='Години Сб–Нд'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name',
            field=models.CharField(blank=True, default='ПП «АФ «Аудит-Перфект»»', max_length=255, verbose_name='Юридична назва'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Якщо порожньо — будується з адреси.', verbose_name='Посилання на карту (Google/Apple)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Додатковий телефон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_secondary_href',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='tel: (додатковий)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, default='', help_text='Username без @ або повне посилання t.me/…', max_length=80, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_directions',
            field=models.TextField(blank=True, default='Метро «Золоті ворота» — 7–8 хвилин пішки\nВхід з боку вул. Велика Житомирська\nПаркування поруч обмежене — зручніше таксі або метро', help_text='Кожен рядок — окремий пункт.', verbose_name='Як дістатися'),
        ),
    ]
