# Generated by Django 5.2.6 on 2026-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_contacts_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteblock',
            options={'ordering': ['page', 'sort_order', 'key'], 'verbose_name': 'Текст сторінки', 'verbose_name_plural': 'Тексти сторінок'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_description',
            field=models.CharField(blank=True, default='ПП «АФ «Аудит-Перфект»»: аудит, облік, ТЦ, КІК, військовий облік та юридичний супровід з 2007 року.', max_length=160, verbose_name='SEO description: Про нас'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_title',
            field=models.CharField(blank=True, default='Про нас — Аудит-Перфект', max_length=70, verbose_name='SEO title: Про нас'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_meta_description',
            field=models.CharField(blank=True, default='Телефон, email, адреса офісу Аудит-Перфект у Києві, графік роботи та як дістатися.', max_length=160, verbose_name='SEO description: Контакти'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_meta_title',
            field=models.CharField(blank=True, default='Контакти — Аудит-Перфект', max_length=70, verbose_name='SEO title: Контакти'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_meta_description',
            field=models.CharField(blank=True, default='Супроводжуємо бізнес у звітності, перевірках і призначенні статусу критично важливого підприємства.', max_length=160, verbose_name='SEO description: Головна'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_meta_title',
            field=models.CharField(blank=True, default='Аудит-Перфект — аудит, облік і супровід бізнесу', max_length=70, verbose_name='SEO title: Головна'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_description',
            field=models.CharField(blank=True, default='Новини та аналітика Аудит-Перфект про аудит, облік і супровід бізнесу.', max_length=160, verbose_name='SEO description: Новини'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_title',
            field=models.CharField(blank=True, default='Новини — Аудит-Перфект', max_length=70, verbose_name='SEO title: Новини'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='policy_meta_description',
            field=models.CharField(blank=True, default='Як Аудит-Перфект обробляє персональні дані відвідувачів сайту.', max_length=160, verbose_name='SEO description: Політика'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='policy_meta_title',
            field=models.CharField(blank=True, default='Політика конфіденційності — Аудит-Перфект', max_length=70, verbose_name='SEO title: Політика'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_description',
            field=models.CharField(blank=True, default='Сім напрямів супроводу бізнесу: аудит, облік, ТЦ, КІК, військовий облік, юридичні та кадрові послуги.', max_length=160, verbose_name='SEO description: Послуги'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_title',
            field=models.CharField(blank=True, default='Послуги — Аудит-Перфект', max_length=70, verbose_name='SEO title: Послуги'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('html', 'HTML'), ('image', 'Зображення')], default='text', max_length=16, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='key',
            field=models.CharField(help_text='Не змінюйте ключ, якщо блок уже на сайті.', max_length=64, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас')], db_index=True, max_length=64, verbose_name='Сторінка'),
        ),
    ]
