# Generated by Django 5.2.6 on 2026-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_page_seo_and_block_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consult_kicker',
            field=models.CharField(default='Контакт', max_length=80, verbose_name='Підпис блоку консультації'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consult_title',
            field=models.CharField(default='Потрібна консультація', max_length=120, verbose_name='Заголовок блоку консультації'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_blurb',
            field=models.TextField(blank=True, default='Аудит, облік, трансфертне ціноутворення, КІК, військовий облік і юридичний супровід — однією командою.', verbose_name='Текст у футері'),
        ),
    ]
