# Generated by Django 5.2.15 on 2026-09-23 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_bg',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Білий'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_blue',
            field=models.CharField(default='#002fa7', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Синій'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_ink',
            field=models.CharField(default='#141824', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Темний'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_red',
            field=models.CharField(default='#ec423c', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Червоний'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_wash',
            field=models.CharField(default='#f7f6f3', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Теплий світлий'),
        ),
    ]
