# Generated by Django 5.2.15 on 2026-09-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_body',
            field=models.CharField(choices=[('onest', 'Onest'), ('manrope', 'Manrope'), ('inter', 'Inter'), ('source-sans-3', 'Source Sans 3'), ('ibm-plex-sans', 'IBM Plex Sans'), ('nunito-sans', 'Nunito Sans'), ('noto-sans', 'Noto Sans'), ('rubik', 'Rubik'), ('fira-sans', 'Fira Sans'), ('wix-madefor-text', 'Wix Madefor Text')], default='manrope', max_length=32, verbose_name='Шрифт тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_display',
            field=models.CharField(choices=[('onest', 'Onest'), ('manrope', 'Manrope'), ('inter', 'Inter'), ('source-sans-3', 'Source Sans 3'), ('ibm-plex-sans', 'IBM Plex Sans'), ('nunito-sans', 'Nunito Sans'), ('noto-sans', 'Noto Sans'), ('rubik', 'Rubik'), ('fira-sans', 'Fira Sans'), ('wix-madefor-text', 'Wix Madefor Text')], default='onest', max_length=32, verbose_name='Шрифт заголовків'),
        ),
    ]
