# Generated by Django 5.2.15 on 2026-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_fonts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='about_meta_description',
            new_name='about_meta_description_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='about_meta_title',
            new_name='about_meta_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='address',
            new_name='address_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='consult_kicker',
            new_name='consult_kicker_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='consult_title',
            new_name='consult_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='contacts_meta_description',
            new_name='contacts_meta_description_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='contacts_meta_title',
            new_name='contacts_meta_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='default_meta_description',
            new_name='default_meta_description_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='default_meta_title',
            new_name='default_meta_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='footer_blurb',
            new_name='footer_blurb_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='home_meta_description',
            new_name='home_meta_description_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='home_meta_title',
            new_name='home_meta_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='hours_note',
            new_name='hours_note_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='hours_weekdays',
            new_name='hours_weekdays_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='hours_weekend',
            new_name='hours_weekend_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='legal_name',
            new_name='legal_name_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='news_meta_description',
            new_name='news_meta_description_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='news_meta_title',
            new_name='news_meta_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='policy_meta_description',
            new_name='policy_meta_description_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='policy_meta_title',
            new_name='policy_meta_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='services_meta_description',
            new_name='services_meta_description_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='services_meta_title',
            new_name='services_meta_title_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='tagline',
            new_name='tagline_uk',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='visit_directions',
            new_name='visit_directions_uk',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_description_en',
            field=models.CharField(blank=True, default='Private Enterprise Audit Firm “Audit-Perfect”: audit, accounting, transfer pricing, CFCs, military registration and legal support since 2007.', max_length=160, verbose_name='SEO description: About'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_title_en',
            field=models.CharField(blank=True, default='About us — Audit-Perfect', max_length=70, verbose_name='SEO title: About'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, default='20 Velyka Zhytomyrska Street, Kyiv', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consult_kicker_en',
            field=models.CharField(blank=True, default='Contact', max_length=80, verbose_name='Consultation kicker'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consult_title_en',
            field=models.CharField(blank=True, default='Need a consultation', max_length=120, verbose_name='Consultation title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_meta_description_en',
            field=models.CharField(blank=True, default='Phone, email and the Audit-Perfect office in Kyiv, opening hours and how to get there.', max_length=160, verbose_name='SEO description: Contacts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_meta_title_en',
            field=models.CharField(blank=True, default='Contacts — Audit-Perfect', max_length=70, verbose_name='SEO title: Contacts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description_en',
            field=models.CharField(blank=True, default='We support businesses with reporting, reviews and critical-enterprise status.', max_length=160, verbose_name='Default SEO description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title_en',
            field=models.CharField(blank=True, default='Audit-Perfect — audit, accounting and business support', max_length=70, verbose_name='Default SEO title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='en_enabled',
            field=models.BooleanField(default=True, verbose_name='Англійська мова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_blurb_en',
            field=models.TextField(blank=True, default='Audit, accounting, transfer pricing, CFCs, military registration and legal support — one team.', verbose_name='Footer text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_meta_description_en',
            field=models.CharField(blank=True, default='We support businesses with reporting, reviews and critical-enterprise status.', max_length=160, verbose_name='SEO description: Home'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_meta_title_en',
            field=models.CharField(blank=True, default='Audit-Perfect — audit, accounting and business support', max_length=70, verbose_name='SEO title: Home'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_note_en',
            field=models.CharField(blank=True, default='Lunch break 13:00–14:00.', max_length=255, verbose_name='Hours note'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_weekdays_en',
            field=models.CharField(blank=True, default='09:00–18:00', max_length=80, verbose_name='Hours Mon–Fri'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_weekend_en',
            field=models.CharField(blank=True, default='Closed', max_length=80, verbose_name='Hours Sat–Sun'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name_en',
            field=models.CharField(blank=True, default='Private Enterprise Audit Firm “Audit-Perfect”', max_length=255, verbose_name='Legal name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_description_en',
            field=models.CharField(blank=True, default='News and analysis from Audit-Perfect on audit, accounting and business support.', max_length=160, verbose_name='SEO description: News'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_title_en',
            field=models.CharField(blank=True, default='News — Audit-Perfect', max_length=70, verbose_name='SEO title: News'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='policy_body_en',
            field=models.TextField(blank=True, default='This website has no enquiry forms. If you call or email us yourself, we use the number and address only to reply.\n\nWe do not sell data or pass it to third parties, except where the law requires it. The text on this page is a draft; the final version should be agreed with counsel.', verbose_name='Privacy text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='policy_body_uk',
            field=models.TextField(blank=True, default='На сайті немає форм заявок. Якщо ви самі телефонуєте або пишете листа, ми використовуємо номер і адресу лише щоб відповісти.\n\nДані не продаємо і не передаємо третім сторонам, крім випадків, яких вимагає закон. Текст на цій сторінці — чернетка; фінальну редакцію погодите з юристом.', verbose_name='Текст політики'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='policy_meta_description_en',
            field=models.CharField(blank=True, default='How Audit-Perfect handles personal data of website visitors.', max_length=160, verbose_name='SEO description: Privacy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='policy_meta_title_en',
            field=models.CharField(blank=True, default='Privacy policy — Audit-Perfect', max_length=70, verbose_name='SEO title: Privacy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_description_en',
            field=models.CharField(blank=True, default='Seven areas of business support: audit, accounting, transfer pricing, CFCs, military registration, legal and HR services.', max_length=160, verbose_name='SEO description: Services'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_title_en',
            field=models.CharField(blank=True, default='Services — Audit-Perfect', max_length=70, verbose_name='SEO title: Services'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, default='Audit firm', max_length=120, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_directions_en',
            field=models.TextField(blank=True, default='Zoloti Vorota metro — 7–8 minutes on foot\nEntrance from Velyka Zhytomyrska Street\nStreet parking nearby is limited — a taxi or the metro is easier', help_text='Кожен рядок — окремий пункт.', verbose_name='Directions'),
        ),
    ]
