# Generated by Django 5.2.15 on 2026-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fill_english'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_name',
            new_name='site_name_uk',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(blank=True, default='AUDYT-PERFECT', max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_meta_description_en',
            field=models.CharField(blank=True, default='Private Enterprise Audit Firm “AUDYT-PERFECT”: audit, accounting, transfer pricing, CFCs, military registration and legal support since 2007.', max_length=160, verbose_name='SEO description: About'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_meta_title_en',
            field=models.CharField(blank=True, default='About us — AUDYT-PERFECT', max_length=70, verbose_name='SEO title: About'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contacts_meta_description_en',
            field=models.CharField(blank=True, default='Phone, email and the AUDYT-PERFECT office in Kyiv, opening hours and how to get there.', max_length=160, verbose_name='SEO description: Contacts'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contacts_meta_title_en',
            field=models.CharField(blank=True, default='Contacts — AUDYT-PERFECT', max_length=70, verbose_name='SEO title: Contacts'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_meta_title_en',
            field=models.CharField(blank=True, default='AUDYT-PERFECT — audit, accounting and business support', max_length=70, verbose_name='Default SEO title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_meta_title_en',
            field=models.CharField(blank=True, default='AUDYT-PERFECT — audit, accounting and business support', max_length=70, verbose_name='SEO title: Home'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='legal_name_en',
            field=models.CharField(blank=True, default='Private Enterprise Audit Firm “AUDYT-PERFECT”', max_length=255, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='news_meta_description_en',
            field=models.CharField(blank=True, default='News and analysis from AUDYT-PERFECT on audit, accounting and business support.', max_length=160, verbose_name='SEO description: News'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='news_meta_title_en',
            field=models.CharField(blank=True, default='News — AUDYT-PERFECT', max_length=70, verbose_name='SEO title: News'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='policy_meta_description_en',
            field=models.CharField(blank=True, default='How AUDYT-PERFECT handles personal data of website visitors.', max_length=160, verbose_name='SEO description: Privacy'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='policy_meta_title_en',
            field=models.CharField(blank=True, default='Privacy policy — AUDYT-PERFECT', max_length=70, verbose_name='SEO title: Privacy'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='services_meta_title_en',
            field=models.CharField(blank=True, default='Services — AUDYT-PERFECT', max_length=70, verbose_name='SEO title: Services'),
        ),
    ]
